[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "tests.settings.django_test_settings"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tests.settings.django_test_settings"

testpaths = ["tests"]
python_files = ["test_*.py", "*_tests.py"]
norecursedirs = [".*", "venv"]
